POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Сырники из творога",
  "preparationTime": 30,
  "ingredients": [
    {
      "title": "Творог",
      "quantity": 350,
      "measureUnit": "гр."
    },
    {
      "title": "Куриное яйцо",
      "quantity": 2,
      "measureUnit": "шт."
    },
    {
      "title": "Пшеничная мука",
      "quantity": 6,
      "measureUnit": "ст. ложек"
    },
    {
      "title": "Сахар",
      "quantity": 2,
      "measureUnit": "ст. ложек"
    }
  ],
  "step":[
    "Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте",
    "Всыпьте в творог муку и тщательно перемешайте",
    "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло",
    "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду",
    "Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния",
    "Повторяйте, пока творог не закончится."
    ]
}

###
GET http://localhost:8080/recipe/0


